# Generated by Django 3.0.4 on 2020-03-29 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body_text', models.TextField()),
                ('created_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
